export const a = {
    type: 'object',
    id: 'urn:jsonschema:com:flightstats:airports:v1:AirportsResponse',
    properties: {
        error: {
            type: 'object',
            id: 'urn:jsonschema:com:flightstats:flex:ApiResponseError',
            properties: {
                httpStatusCode: { type: 'integer' },
                errorId: { type: 'string' },
                errorMessage: { type: 'string' },
                errorCode: { type: 'string' },
            },
        },
        airports: {
            type: 'array',
            items: {
                type: 'object',
                id: 'urn:jsonschema:com:flightstats:flex:Airport',
                properties: {
                    fs: { type: 'string' },
                    iata: { type: 'string' },
                    icao: { type: 'string' },
                    faa: { type: 'string' },
                    name: { type: 'string' },
                    street1: { type: 'string' },
                    street2: { type: 'string' },
                    city: { type: 'string' },
                    cityCode: { type: 'string' },
                    stateCode: { type: 'string' },
                    postalCode: { type: 'string' },
                    countryCode: { type: 'string' },
                    district: { type: 'string' },
                    countryName: { type: 'string' },
                    regionName: { type: 'string' },
                    timeZoneRegionName: { type: 'string' },
                    weatherZone: { type: 'string' },
                    localTime: { type: 'string' },
                    utcOffsetHours: { type: 'number' },
                    latitude: { type: 'number' },
                    longitude: { type: 'number' },
                    elevationFeet: { type: 'integer' },
                    classification: { type: 'integer' },
                    active: { type: 'boolean' },
                    dateFrom: { type: 'string' },
                    dateTo: { type: 'string' },
                    weatherUrl: { type: 'string' },
                    delayIndexUrl: { type: 'string' },
                },
            },
        },
        airport: {
            type: 'object',
            $ref: 'urn:jsonschema:com:flightstats:flex:Airport',
        },
    },
};
