import { IResponse, IResponseDataItem } from '../response.types';

export const DATA_2 = {
    flight_date: '2021-11-17',
    flight_status: 'scheduled',
    departure: {
        airport: 'Guangzhou Baiyun International',
        timezone: 'Asia/Shanghai',
        iata: 'CAN',
        icao: 'ZGGG',
        terminal: null,
        gate: null,
        delay: null,
        scheduled: '2021-11-17T05:00:00+00:00',
        estimated: '2021-11-17T05:00:00+00:00',
        actual: null,
        estimated_runway: null,
        actual_runway: null,
    },
    arrival: {
        airport: 'Xianyang',
        timezone: 'Asia/Shanghai',
        iata: 'XIY',
        icao: 'ZLXY',
        terminal: '3',
        gate: null,
        baggage: null,
        delay: null,
        scheduled: '2021-11-17T07:35:00+00:00',
        estimated: '2021-11-17T07:35:00+00:00',
        actual: null,
        estimated_runway: null,
        actual_runway: null,
    },
    airline: { name: 'Longhao Airlines', iata: 'GI', icao: 'LHA' },
    flight: {
        number: '4022',
        iata: 'GI4022',
        icao: 'LHA4022',
        codeshared: null,
    },
    aircraft: null,
    live: null,
};

export const DATA_1: IResponse = {
    pagination: {
        limit: 100,
        offset: 0,
        count: 100,
        total: 1669022,
    },
    data: [
        {
            flight_date: '2019-12-12',
            flight_status: 'active',
            departure: {
                airport: 'San Francisco International',
                timezone: 'America/Los_Angeles',
                iata: 'SFO',
                icao: 'KSFO',
                terminal: '2',
                gate: 'D11',
                delay: 13,
                scheduled: '2019-12-12T04:20:00+00:00',
                estimated: '2019-12-12T04:20:00+00:00',
                actual: '2019-12-12T04:20:13+00:00',
                estimated_runway: '2019-12-12T04:20:13+00:00',
                actual_runway: '2019-12-12T04:20:13+00:00',
            },
            arrival: {
                airport: 'Dallas/Fort Worth International',
                timezone: 'America/Chicago',
                iata: 'DFW',
                icao: 'KDFW',
                terminal: 'A',
                gate: 'A22',
                baggage: 'A17',
                delay: 0,
                scheduled: '2019-12-12T04:20:00+00:00',
                estimated: '2019-12-12T04:20:00+00:00',
                actual: null,
                estimated_runway: null,
                actual_runway: null,
            },
            airline: {
                name: 'American Airlines',
                iata: 'AA',
                icao: 'AAL',
            },
            flight: {
                number: '1004',
                iata: 'AA1004',
                icao: 'AAL1004',
                codeshared: null,
            },
            aircraft: {
                registration: 'N160AN',
                iata: 'A321',
                icao: 'A321',
                icao24: 'A0F1BB',
            },
            live: {
                updated: '2019-12-12T10:00:00+00:00',
                latitude: 36.2856,
                longitude: -106.807,
                altitude: 8846.82,
                direction: 114.34,
                speed_horizontal: 894.348,
                speed_vertical: 1.188,
                is_ground: false,
            },
        },
    ],
};
